apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-verse-plagiat-worker
spec:
  selector:
    matchLabels:
      app: uni-verse-plagiat-worker
  template:
    metadata:
      labels:
        app: uni-verse-plagiat-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: uni-verse-plagiat-worker
        image: registry.qtmsheep.com/vagahbond/uni-verse/worker
        env:
          - name: TASK
            value: plagiat
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
          - configMapRef:
              name: uni-verse-conf
        volumeMounts:
        - mountPath: /root/.olaf/db
          name: uni-verse-worker-db


      volumes:
      - name: uni-verse-worker-db
        persistentVolumeClaim:
          claimName:  uni-verse-worker-db
