name: build

on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Build
        run: |
          docker build --tag registry.qtmsheep.com/vagahbond/uni-verse/worker:latest --tag registry.qtmsheep.com/vagahbond/uni-verse/worker . # will run buildx
