name: release

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: |
          docker build --tag ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/worker:latest --tag ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/worker:${{ steps.tag_name.outputs.TAG_NAME }} . # will run buildx

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/worker:${{ steps.tag_name.outputs.TAG_NAME }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/worker:latest

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/worker
      #       ${{ secrets.DOCKER_REGISTRY }}/vagahbond/uni-verse/worker:${{ steps.tag_name.outputs.TAG_NAME }}
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

